# Generated by Django 4.0.2 on 2022-02-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_category_portal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portal.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
